### PR TITLE
allow to set layer via 'layer' GET param

### PR DESCRIPTION
**Pull request by sorki**
To be able to point to ttnmapper with 'layer' parameter as the default map often doesn't even contain name of our cities.

This repo doesn't seem to match deployed website so please port/update if needed.

### CODE REVIEW

**Comment by jpmeijers** [comment]
Ahh excellent. Thanks for this awesome feature! I'll merge the PR in as soon as I put the feature into production.

**Comment by jpmeijers** [comment]
Functionality has been added to production. Will add it to this repo when we sync from production here.

**Comment by sorki** [comment]
Cool, it works! You can see it action at https://iot.otevrenamesta.cz/ 

Gateway name points to e.g.
https://ttnmapper.org/?lat=49.20410354&lon=16.59441639&zoom=15&type=radar&layer=mapnik

**Comment by jpmeijers** [comment]
Your code snippet got lost somewhere, but it has been added back in to the production code base now.

**Comment by sorki** [comment]
Works fine now, thanks!

**Pull request closed without merging**
